name: Assign Issue
on:
  issues:
    types: [opened]
permissions:
  issues: write  # Explicitly grants write permission to manage issues
jobs:
  assign_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue
        uses: actions-ecosystem/action-assign@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: noahschmal
